apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: traefik

name: traefik
chartHome: ../../charts
releaseName: traefik
namespace: gateway
includeCRDs: true
valuesInline:
  deployment:
    kind: DaemonSet
  ports:
    web:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: cert-manager

name: cert-manager
chartHome: ../../charts
releaseName: cert-manager
namespace: gateway
includeCRDs: true
valuesInline:
  installCRDs: true
