apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: gateway

name: traefik
chartHome: ../../charts
releaseName: gateway
namespace: gateway
includeCRDs: true
valuesInline:
  additionalArguments:
    - --entryPoints.websecure.transport.respondingTimeouts.readTimeout=0
  experimental:
    plugins:
      traefik-oidc-auth:
        moduleName: github.com/sevensolutions/traefik-oidc-auth
        version: v0.16.0
  service:
    spec:
      trafficDistribution: PreferClose
  deployment:
    kind: DaemonSet
  ports:
    web:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: cert-manager

name: cert-manager
chartHome: ../../charts
releaseName: cert-manager
namespace: gateway
includeCRDs: true
valuesInline:
  installCRDs: true
