keys:
  - &tablet age1p9vcj2y2q59reuswpwjdqj8j3gz5yhz77qm9qeua4f5cc3xe8gqqf698t8
  - &test1 age1ezese4ves3ljkzs4rzlmsleq7ea65es0442rc99f7xdxgfazrgfsxe3e7w
  - &test2 age1dq5nmfylgv0te5y3krkz4jeecpgrq8x6x26tukxz2pz2fwtpu54smwpp05
  - &test3 age1k92ahk85plpucmsulfnypqs7nq6jd9yjryr6er9w6gsg8u5tt4tq82zr8t

creation_rules:
  - path_regex: src/.+/secrets.yaml$
    key_groups:
      - age:
        - *tablet
        - *test1
        - *test2
        - *test3
