keys:
  - &tablet age1p9vcj2y2q59reuswpwjdqj8j3gz5yhz77qm9qeua4f5cc3xe8gqqf698t8
  - &cola   age1xzeru626ugw2znueqy034nme56fvf29pq2q3zq4609ajdn2hvdjqnm3vtu
  - &hk     age1efsd4ax034a5kwa092tg5puv4dg0hpxyt45dlytn5c5g6dwml9ysnhhsfa
  - &home   age1vzu6hgq87xqz3k352x0x4mz6n63p32xgwt0ek7cha6sfjusxacgqydx8rr
  - &trunc  age1p9906crzyha38je9a9zx6zpzlqrff9kpr44euwxlf8gg8n8tva8s5x0ujk

creation_rules:
  - path_regex: src/.+/secrets.yaml$
    key_groups:
      - age:
        - *tablet
        - *cola
        - *hk
        - *home
        - *trunc
