keys:
  - &tablet age1p9vcj2y2q59reuswpwjdqj8j3gz5yhz77qm9qeua4f5cc3xe8gqqf698t8
  - &test1 age1tgtvvltsr8kg0jsmzxua4z6u22kpt8f320j42anp9hz74qgmxc4s9trhe7
  - &test2 age1mql7wjernmhtqq69yy7zhaeayvwjcegrvhujzrymmx0x8gd9p5vqhnmp2p
  - &test3 age1tnl05jvur44jc23nl45fzxldfg2p2l0vlw9v3vp2qmf7fktfeausec6hm0

creation_rules:
  - path_regex: src/.+/secrets.yaml$
    key_groups:
      - age:
        - *tablet
        - *test1
        - *test2
        - *test3
