keys:
  - &tablet age1p9vcj2y2q59reuswpwjdqj8j3gz5yhz77qm9qeua4f5cc3xe8gqqf698t8
  - &test1 age1rt63hzfvuflhu5wzcuu55af0tkkdn60lax2c9p0v8drue9sf2qzqyne6my
  - &test2 age1vsxjltg3f2s0wamhq7skpafgrspuuw6mww5pnq9ctschmrkqfygqdwa6jv

creation_rules:
  - path_regex: src/.+/secrets.yaml$
    key_groups:
      - age:
        - *tablet
        - *test1
        - *test2
