keys:
  - &tablet age1p9vcj2y2q59reuswpwjdqj8j3gz5yhz77qm9qeua4f5cc3xe8gqqf698t8
  - &t1     age1neqm6r503dzavrt909wyz0lhw9r5mhe9qcxtfssvw4v6dlfm534s6js7jr
  - &t2     age1vgvy63ryswvvd4tugtzxn6a7q369nkqdqrj6xp29079sk7w6qqjqe3dglk
  - &t3     age1uw4y9q0kgw93yfruvq2dk4lhy9de84n0sgcgssftav9upwkhag8srhq7j7
  - &t4     age1xzw9uaryql8gyfr0x398evtj2jf8uy829fgcdkapqy5qwtexnprqqff66d

creation_rules:
  - path_regex: src/.+/secrets.yaml$
    key_groups:
      - age:
        - *tablet
        - *t1
        - *t2
        - *t3
        - *t4
