keys:
  - &tablet age1p9vcj2y2q59reuswpwjdqj8j3gz5yhz77qm9qeua4f5cc3xe8gqqf698t8
  - &a1 age1vuka6223lfmtu0ez8el2pwpfvwx7xdl0tkf5lpue04xf6l4pmehqnyrsz3
  - &a2 age1g5h2wezct5apm0rqpvsnq363c7guz3zr5v3qptw5jf04rvha2gxql6ht82
  - &a3 age1szvhtd2s00sg3k6g05cgtay7knnm3luwucwnzynkx9yj8dzzef9s0elqud

creation_rules:
  - path_regex: src/.+/secrets.yaml$
    key_groups:
      - age:
        - *tablet
        - *a1
        - *a2
        - *a3
