keys:
  - &tablet age1p9vcj2y2q59reuswpwjdqj8j3gz5yhz77qm9qeua4f5cc3xe8gqqf698t8
  - &template age1hecw4msymtrjrw5pjvv53am9atxx90ph3e9axrkrgr48f0k45g7qqm4vpz

creation_rules:
  - path_regex: src/.+/secrets.yaml$
    key_groups:
      - age:
        - *tablet
        - *template
