apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: argocd

name: argocd
chartHome: ../../charts
releaseName: argocd
namespace: argocd
includeCRDs: true
valuesInline:
  global:
    domain: cd.kagari.org
  server:
    extraArgs:
      - --insecure
  configs:
    cm:
      kustomize.buildOptions: --enable-helm --enable-alpha-plugins --enable-exec
      oidc.config: |
        name: dex
        issuer: https://dex.kagari.org
        clientID: argocd
        enablePKCEAuthentication: true
        requestedScopes: ["openid", "profile", "email", "groups"]
    rbac:
      policy.csv: |
        g, argocd_admin, role:admin
  repoServer:
    # https://github.com/viaduct-ai/kustomize-sops?tab=readme-ov-file#argo-cd-helm-chart-with-custom-tooling
    volumes:
      - name: custom-tools
        emptyDir: {}
    initContainers:
      - name: install-ksops
        image: viaductoss/ksops:v4.3.3
        command: ["/bin/sh", "-c"]
        args:
          - echo "Installing KSOPS...";
            mv ksops /custom-tools/;
            mv kustomize /custom-tools/;
            echo "Done.";
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools
    volumeMounts:
      - mountPath: /usr/local/bin/kustomize
        name: custom-tools
        subPath: kustomize
      - mountPath: /usr/local/bin/ksops
        name: custom-tools
        subPath: ksops
    env:
      - name: SOPS_AGE_KEY
        valueFrom:
          secretKeyRef:
            name: argocd-age-secret
            key: key
