apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec:
  secretName: argocd-cert
  issuerRef:
    name: le-issuer
    kind: ClusterIssuer
  dnsNames:
    - cd.kagari.org
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-ingress
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`cd.kagari.org`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`cd.kagari.org`) && Header(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
  tls:
    secretName: argocd-cert
---
apiVersion: dex.coreos.com/v1
kind: OAuth2Client
metadata:
  name: mfzgo33dmtf7fhheqqrcgji
  namespace: dex
name: argocd
id: argocd
public: true
redirectURIs:
  - https://cd.kagari.org/pkce/verify
  # for argo-cd CLI
  - http://localhost:8085/auth/callback
