apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: longhorn

name: longhorn
chartHome: ../../charts
releaseName: longhorn
namespace: longhorn-system
skipHooks: true
includeCRDs: true
valuesInline:
  longhornUI:
    replicas: 1
  persistence:
    reclaimPolicy: Retain
    defaultDataLocality: strict-local
    defaultClassReplicaCount: 1
    defaultDiskSelector:
      enable: true
      selector: default
  defaultSettings:
    createDefaultDiskLabeledNodes: true
  networkPolicies:
    enabled: true
