apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: longhorn-basic-auth
  namespace: longhorn-system
spec:
  basicAuth:
    secret: longhorn-basic-auth-secret
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
  annotations:
    kubernetes.io/ingress.class: internal-traefik
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`longhorn.kagari.org`)
      middlewares:
        - name: longhorn-basic-auth
      services:
        - name: longhorn-frontend
          port: 80
---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: longhorn-policy
  namespace: longhorn-system
spec:
  podSelector: app == 'longhorn-ui'
  types:
    - Ingress
  ingress:
    - action: Allow
      source:
        namespaceSelector: kubernetes.io/metadata.name == 'internal-gateway'
