apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-cert
  namespace: longhorn-system
spec:
  secretName: longhorn-cert
  issuerRef:
    name: le-issuer
    kind: ClusterIssuer
  dnsNames:
    - longhorn.kagari.org
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: longhorn-oidc
  namespace: longhorn-system
spec:
  plugin:
    traefik-oidc-auth:
      Provider:
        Url: https://dex.kagari.org
        ClientId: longhorn
        UsePkce: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`longhorn.kagari.org`)
      middlewares:
        - name: longhorn-oidc
      services:
        - name: longhorn-frontend
          port: 80
  tls:
    secretName: longhorn-cert
---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: longhorn-policy
  namespace: longhorn-system
spec:
  podSelector: app == 'longhorn-ui'
  types:
    - Ingress
  ingress:
    - action: Allow
      source:
        namespaceSelector: kubernetes.io/metadata.name == 'gateway'
---
apiVersion: dex.coreos.com/v1
kind: OAuth2Client
metadata:
  name: nrxw4z3in5zg5s7sttsiiirdeu
  namespace: dex
name: longhorn
id: longhorn
public: true
redirectURIs:
  - https://longhorn.kagari.org/oidc/callback
