apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: longhorn-oidc
  namespace: longhorn-system
spec:
  plugin:
    traefik-oidc-auth:
      Secret: urn:k8s:secret:longhorn-oidc-secrets:secret
      Provider:
        Url: https://dex.kagari.org
        ClientId: longhorn
        ClientSecret: urn:k8s:secret:longhorn-oidc-secrets:client-secret
      SessionCookie:
        Secure: false
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
  annotations:
    kubernetes.io/ingress.class: internal-traefik
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`longhorn.kagari.org`)
      middlewares:
        - name: longhorn-oidc
      services:
        - name: longhorn-frontend
          port: 80
---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: longhorn-policy
  namespace: longhorn-system
spec:
  podSelector: app == 'longhorn-ui'
  types:
    - Ingress
  ingress:
    - action: Allow
      source:
        namespaceSelector: kubernetes.io/metadata.name == 'internal-gateway'
