apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./resources/namespaces.yaml
  - ./resources/coredns.yaml

helmCharts:
  - name: calico
    namespace: tigera-operator
    skipHooks: true
    includeCRDs: true
    valuesInline:
      installation:
        enabled: true
        calicoNetwork:
          nodeAddressAutodetectionV4:
            firstFound: false
            kubernetes: NodeInternalIP
  - name: longhorn
    namespace: longhorn-system
    skipHooks: true
    includeCRDs: true
