apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./resources/namespaces.yaml
  - ./resources/coredns.yaml
  - ./resources/gateway.yaml

patches:
  - patch: |-
      - op: replace
        path: /kind
        value: DaemonSet
      - op: remove
        path: /spec/replicas
      - op: remove
        path: /spec/strategy
    target:
      kind: Deployment
      name: coredns

helmCharts:
  - name: calico
    releaseName: calico
    namespace: tigera-operator
    skipHooks: true
    includeCRDs: true
    valuesInline:
      installation:
        enabled: true
        calicoNetwork:
          nodeAddressAutodetectionV4:
            firstFound: false
            kubernetes: NodeInternalIP
  - name: coredns
    releaseName: coredns
    namespace: coredns
    skipHooks: true
    includeCRDs: true
    valuesInline:
      service:
        clusterIP: 10.43.0.10
  - name: longhorn
    releaseName: longhorn
    namespace: longhorn-system
    skipHooks: true
    includeCRDs: true
  - name: traefik
    releaseName: traefik
    namespace: gateway
    skipHooks: true
    includeCRDs: true
    valuesInline:
      deployment:
        kind: DaemonSet
  - name: cert-manager
    releaseName: cert-manager
    namespace: gateway
    skipHooks: true
    includeCRDs: true
    valuesInline:
      installCRDs: true
