# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  calico = {
    pname = "calico";
    version = "3.30.1";
    src = fetchurl {
      url = "https://github.com/projectcalico/calico/releases/download/v3.30.1/tigera-operator-v3.30.1.tgz";
      sha256 = "sha256-A9h6+bCq4U4P+PptSDLF6Jp3JJ9gppKD3Qh4iv3GWfc=";
    };
    path = "tigera-operator";
  };
  cert-manager = {
    pname = "cert-manager";
    version = "1.17.2";
    src = fetchurl {
      url = "https://charts.jetstack.io/charts/cert-manager-v1.17.2.tgz";
      sha256 = "sha256-n46q2nhahwESx7GHSVK36Hdv0GZgg2HIPs7oWTFDk60=";
    };
    path = "cert-manager";
  };
  longhorn = {
    pname = "longhorn";
    version = "1.9.0";
    src = fetchurl {
      url = "https://github.com/longhorn/longhorn/releases/download/v1.9.0/charts.tar.gz";
      sha256 = "sha256-mqW8zHeBRRyXVrjCqMgIFH8EGCGEggdjN1qIAmVXaPc=";
    };
    path = "charts/longhorn";
  };
  traefik = {
    pname = "traefik";
    version = "36.0.0";
    src = fetchurl {
      url = "https://traefik.github.io/charts/traefik/traefik-36.0.0.tgz";
      sha256 = "sha256-hekZQYQW45LuTus+/acgzOxjRnc+308XQRd+nOCHSw8=";
    };
    path = "traefik";
  };
}
