# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  calico = {
    pname = "calico";
    version = "3.30.1";
    src = fetchurl {
      url = "https://github.com/projectcalico/calico/releases/download/v3.30.1/tigera-operator-v3.30.1.tgz";
      sha256 = "sha256-A9h6+bCq4U4P+PptSDLF6Jp3JJ9gppKD3Qh4iv3GWfc=";
    };
    path = "tigera-operator";
  };
  coredns = {
    pname = "coredns";
    version = "1.42.2";
    src = fetchurl {
      url = "https://github.com/coredns/helm/releases/download/coredns-1.42.2/coredns-1.42.2.tgz";
      sha256 = "sha256-+X3hdIb1u9i6WfkJfSDeC7uFsIHIVICUzEfnzxQpca0=";
    };
    path = "coredns";
  };
  longhorn = {
    pname = "longhorn";
    version = "1.9.0";
    src = fetchurl {
      url = "https://github.com/longhorn/longhorn/releases/download/v1.9.0/charts.tar.gz";
      sha256 = "sha256-mqW8zHeBRRyXVrjCqMgIFH8EGCGEggdjN1qIAmVXaPc=";
    };
    path = "charts/longhorn";
  };
}
