apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: external-traefik

name: traefik
chartHome: ../../charts
releaseName: external-traefik
namespace: external-gateway
# added in internal-gateway
# includeCRDs: true
valuesInline:
  ingressClass:
    isDefaultClass: false
  deployment:
    kind: DaemonSet
  ports:
    web:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: external-cert-manager

name: cert-manager
chartHome: ../../charts
releaseName: external-cert-manager
namespace: external-gateway
includeCRDs: true
valuesInline:
  installCRDs: true
