apiVersion: v1
kind: Namespace
metadata:
  name: external-gateway
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-issuer
  namespace: external-gateway
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: le-issuer
    solvers:
      - http01:
          ingress:
            ingressClassName: external-traefik
