apiVersion: v1
kind: Namespace
metadata:
  name: tigera-operator
---
apiVersion: projectcalico.org/v3
kind: KubeControllersConfiguration
metadata:
  name: default
spec:
  controllers:
    loadBalancer:
      assignIPs: RequestedServicesOnly
---
# use 10.42.0.0/16 for workload IP pool (same with --cluster-cidr of k3s)

apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: calico-workload-ippool
spec:
  cidr: 10.42.0.0/17
  blockSize: 26
  natOutgoing: true
  assignmentMode: Automatic
  allowedUses:
    - Workload
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: calico-workload-ippool-singbox-bypass
spec:
  # should be consistent with the singbox-bypass-cidr in nixos config
  cidr: 10.42.128.0/17
  blockSize: 26
  natOutgoing: true
  assignmentMode: Manual
  allowedUses:
    - Workload
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: calico-loadbalacer-ippool
spec:
  cidr: 10.11.1.0/24
  blockSize: 27
  assignmentMode: Manual
  allowedUses:
    - LoadBalancer
---
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  serviceLoadBalancerIPs:
    - cidr: 10.11.1.0/24
