apiVersion: v1
kind: Namespace
metadata:
  name: tigera-operator
---
apiVersion: projectcalico.org/v3
kind: KubeControllersConfiguration
metadata:
  name: default
spec:
  controllers:
    loadBalancer:
      assignIPs: RequestedServicesOnly
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: calico-workload-ippool
spec:
  # make the same with --cluster-cidr of k3s
  cidr: 10.42.0.0/16
  blockSize: 26
  assignmentMode: Automatic
  allowedUses:
    - Workload
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: calico-loadbalacer-ippool
spec:
  cidr: 10.11.1.0/24
  blockSize: 27
  assignmentMode: Manual
  allowedUses:
    - LoadBalancer
---
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  serviceLoadBalancerIPs:
    - cidr: 10.11.1.0/24
