apiVersion: v1
kind: Namespace
metadata:
  name: tigera-operator
---
apiVersion: projectcalico.org/v3
kind: KubeControllersConfiguration
metadata:
  name: default
spec:
  controllers:
    loadBalancer:
      assignIPs: RequestedServicesOnly
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: calico-ippool
spec:
  cidr: 10.11.1.0/24
  blockSize: 27
  assignmentMode: Manual
  allowedUses:
    - LoadBalancer
---
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  serviceLoadBalancerIPs:
    - cidr: 10.11.1.0/24
