apiVersion: v1
kind: Namespace
metadata:
  name: dex
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dex-cert
  namespace: dex
spec:
  secretName: dex-cert
  issuerRef:
    name: le-issuer
    kind: ClusterIssuer
  dnsNames:
    - dex.kagari.org
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dex-ingress
  namespace: dex
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`dex.kagari.org`)
      services:
        - name: dex
          port: 5556
  tls:
    secretName: dex-cert

