apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: internal-traefik

name: traefik
chartHome: ../../charts
releaseName: internal-traefik
namespace: internal-gateway
includeCRDs: true
valuesInline:
  additionalArguments:
    - --providers.kubernetesingress.ingressclass=internal-traefik
    - --providers.kubernetescrd.ingressclass=internal-traefik
    - --entryPoints.websecure.transport.respondingTimeouts.readTimeout=0
  service:
    spec:
      trafficDistribution: PreferClose
      externalTrafficPolicy: Local
      # make servicelb ignore this service, calico will not read this field
      # https://github.com/projectcalico/calico/issues/10544
      # https://github.com/kubernetes/cloud-provider/blob/2266dcc5607ab8701b7c7ab654c57b86a188a5df/controllers/service/controller.go#L864
      loadBalancerClass: "calico"
    annotations:
      projectcalico.org/loadBalancerIPs: '["10.11.1.1"]'
  deployment:
    kind: DaemonSet
