# TODO: url -> tarball https://github.com/NixOS/nix/issues/10575

[calico]
src.manual = "3.30.1"
fetch.url = "https://github.com/projectcalico/calico/releases/download/v$ver/tigera-operator-v$ver.tgz"
passthru.path = "tigera-operator"

[coredns]
src.manual = "1.42.2"
fetch.url = "https://github.com/coredns/helm/releases/download/coredns-$ver/coredns-$ver.tgz"
passthru.path = "coredns"

[longhorn]
src.manual = "1.9.0"
fetch.url = "https://github.com/longhorn/longhorn/releases/download/v$ver/charts.tar.gz"
passthru.path = "charts/longhorn"

[traefik]
src.manual = "36.0.0"
fetch.url = "https://traefik.github.io/charts/traefik/traefik-$ver.tgz"
passthru.path = "traefik"

[cert-manager]
src.manual = "1.17.2"
fetch.url = "https://charts.jetstack.io/charts/cert-manager-v$ver.tgz"
passthru.path = "cert-manager"
