# TODO: url -> tarball https://github.com/NixOS/nix/issues/10575

[calico]
src.manual = "3.30.1"
fetch.url = "https://github.com/projectcalico/calico/releases/download/v$ver/tigera-operator-v$ver.tgz"
passthru.path = "tigera-operator"

[longhorn]
src.manual = "1.9.0"
fetch.url = "https://github.com/longhorn/longhorn/releases/download/v$ver/charts.tar.gz"
passthru.path = "charts/longhorn"
